# This file was auto-generated by Fern from our API Definition.

import typing

from ...core import enum

T_Result = typing.TypeVar("T_Result")


class BlobStorageExportFieldGroup(enum.StrEnum):
    """
    Field group selecting which observation columns are included in the export. Applies to all export sources; groups without a counterpart in the legacy data model (e.g. `trace_context`) are omitted from the legacy observations export.
    """

    CORE = "core"
    BASIC = "basic"
    TIME = "time"
    IO = "io"
    METADATA = "metadata"
    MODEL = "model"
    USAGE = "usage"
    PROMPT = "prompt"
    METRICS = "metrics"
    TOOLS = "tools"
    TRACE_CONTEXT = "trace_context"

    def visit(
        self,
        core: typing.Callable[[], T_Result],
        basic: typing.Callable[[], T_Result],
        time: typing.Callable[[], T_Result],
        io: typing.Callable[[], T_Result],
        metadata: typing.Callable[[], T_Result],
        model: typing.Callable[[], T_Result],
        usage: typing.Callable[[], T_Result],
        prompt: typing.Callable[[], T_Result],
        metrics: typing.Callable[[], T_Result],
        tools: typing.Callable[[], T_Result],
        trace_context: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is BlobStorageExportFieldGroup.CORE:
            return core()
        if self is BlobStorageExportFieldGroup.BASIC:
            return basic()
        if self is BlobStorageExportFieldGroup.TIME:
            return time()
        if self is BlobStorageExportFieldGroup.IO:
            return io()
        if self is BlobStorageExportFieldGroup.METADATA:
            return metadata()
        if self is BlobStorageExportFieldGroup.MODEL:
            return model()
        if self is BlobStorageExportFieldGroup.USAGE:
            return usage()
        if self is BlobStorageExportFieldGroup.PROMPT:
            return prompt()
        if self is BlobStorageExportFieldGroup.METRICS:
            return metrics()
        if self is BlobStorageExportFieldGroup.TOOLS:
            return tools()
        if self is BlobStorageExportFieldGroup.TRACE_CONTEXT:
            return trace_context()
