# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import UniversalBaseModel
from ...core.serialization import FieldMetadata
from .blob_storage_sync_status import BlobStorageSyncStatus


class BlobStorageIntegrationStatusResponse(UniversalBaseModel):
    id: str
    project_id: typing_extensions.Annotated[str, FieldMetadata(alias="projectId")]
    sync_status: typing_extensions.Annotated[
        BlobStorageSyncStatus, FieldMetadata(alias="syncStatus")
    ]
    enabled: bool
    last_sync_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime], FieldMetadata(alias="lastSyncAt")
    ] = pydantic.Field(default=None)
    """
    End of the last successfully exported time window. Compare against your ETL bookmark to determine if new data is available. Null if the integration has never synced.
    """

    next_sync_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime], FieldMetadata(alias="nextSyncAt")
    ] = pydantic.Field(default=None)
    """
    When the next export is scheduled. Null if no sync has occurred yet.
    """

    last_error: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="lastError")
    ] = pydantic.Field(default=None)
    """
    Raw error message from the storage provider (S3/Azure/GCS) if the last export failed. Cleared on successful export.
    """

    last_error_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime], FieldMetadata(alias="lastErrorAt")
    ] = pydantic.Field(default=None)
    """
    When the last error occurred. Cleared on successful export.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )
