# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import UniversalBaseModel
from ...core.serialization import FieldMetadata
from .blob_storage_export_field_group import BlobStorageExportFieldGroup
from .blob_storage_export_frequency import BlobStorageExportFrequency
from .blob_storage_export_mode import BlobStorageExportMode
from .blob_storage_export_source import BlobStorageExportSource
from .blob_storage_integration_file_type import BlobStorageIntegrationFileType
from .blob_storage_integration_type import BlobStorageIntegrationType


class CreateBlobStorageIntegrationRequest(UniversalBaseModel):
    project_id: typing_extensions.Annotated[str, FieldMetadata(alias="projectId")] = (
        pydantic.Field()
    )
    """
    ID of the project in which to configure the blob storage integration
    """

    type: BlobStorageIntegrationType
    bucket_name: typing_extensions.Annotated[str, FieldMetadata(alias="bucketName")] = (
        pydantic.Field()
    )
    """
    Name of the storage bucket. For AZURE_BLOB_STORAGE, must be a valid Azure container name (3-63 chars, lowercase letters, numbers, and hyphens only, must start and end with a letter or number, no consecutive hyphens).
    """

    endpoint: typing.Optional[str] = pydantic.Field(default=None)
    """
    Custom endpoint URL (required for S3_COMPATIBLE type)
    """

    region: str = pydantic.Field()
    """
    Storage region
    """

    access_key_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="accessKeyId")
    ] = pydantic.Field(default=None)
    """
    Access key ID for authentication
    """

    secret_access_key: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="secretAccessKey")
    ] = pydantic.Field(default=None)
    """
    Secret access key for authentication (will be encrypted when stored)
    """

    prefix: typing.Optional[str] = pydantic.Field(default=None)
    """
    Path prefix for exported files (must end with forward slash if provided)
    """

    export_frequency: typing_extensions.Annotated[
        BlobStorageExportFrequency, FieldMetadata(alias="exportFrequency")
    ]
    enabled: bool = pydantic.Field()
    """
    Whether the integration is active
    """

    force_path_style: typing_extensions.Annotated[
        bool, FieldMetadata(alias="forcePathStyle")
    ] = pydantic.Field()
    """
    Use path-style URLs for S3 requests
    """

    file_type: typing_extensions.Annotated[
        BlobStorageIntegrationFileType, FieldMetadata(alias="fileType")
    ]
    export_mode: typing_extensions.Annotated[
        BlobStorageExportMode, FieldMetadata(alias="exportMode")
    ]
    export_start_date: typing_extensions.Annotated[
        typing.Optional[dt.datetime], FieldMetadata(alias="exportStartDate")
    ] = pydantic.Field(default=None)
    """
    Custom start date for exports (required when exportMode is FROM_CUSTOM_DATE)
    """

    compressed: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Enable gzip compression for exported files (.csv.gz, .json.gz, .jsonl.gz). Defaults to true.
    """

    export_source: typing_extensions.Annotated[
        typing.Optional[BlobStorageExportSource], FieldMetadata(alias="exportSource")
    ] = pydantic.Field(default=None)
    """
    Data to export. When omitted on update, the existing value is preserved. When omitted on create: pre-cutoff Cloud projects and self-hosted deployments fall back to `LEGACY_TRACES_OBSERVATIONS`; post-cutoff Cloud projects (created on or after 2026-05-20) auto-default to `OBSERVATIONS_V2`. Required when `exportFieldGroups` is provided.
    
    **Cloud-only deprecation gate (effective 2026-05-20):** For projects created on or after 2026-05-20 on Langfuse Cloud, `LEGACY_TRACES_OBSERVATIONS` and `LEGACY_TRACES_AND_ENRICHED_OBSERVATIONS` are rejected with HTTP 400. Omitting `exportSource` on these projects silently defaults to `OBSERVATIONS_V2` rather than the schema column default. Use `OBSERVATIONS_V2` for all new integrations. Projects created before 2026-05-20 and self-hosted deployments are unaffected.
    """

    export_field_groups: typing_extensions.Annotated[
        typing.Optional[typing.List[BlobStorageExportFieldGroup]],
        FieldMetadata(alias="exportFieldGroups"),
    ] = pydantic.Field(default=None)
    """
    Field groups to include in each exported row.
    
    For exportSource `OBSERVATIONS_V2` or `LEGACY_TRACES_AND_ENRICHED_OBSERVATIONS`: must include `core` if provided. When omitted on create, the column default (all groups) applies. When omitted on update, the existing value is preserved.
    
    For exportSource `LEGACY_TRACES_OBSERVATIONS`: this field must be omitted or null. Sending an array (including an empty array) returns 400, because that source uses a fixed column set and does not honor field groups.
    
    `exportFieldGroups` requires `exportSource` to be provided in the same request.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )
