# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import UniversalBaseModel
from ...core.serialization import FieldMetadata
from .score_source import ScoreSource


class BaseScore(UniversalBaseModel):
    id: str
    trace_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="traceId")
    ] = pydantic.Field(default=None)
    """
    The trace ID associated with the score
    """

    session_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="sessionId")
    ] = pydantic.Field(default=None)
    """
    The session ID associated with the score
    """

    observation_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="observationId")
    ] = pydantic.Field(default=None)
    """
    The observation ID associated with the score
    """

    dataset_run_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="datasetRunId")
    ] = pydantic.Field(default=None)
    """
    The dataset run ID associated with the score
    """

    name: str
    source: ScoreSource
    timestamp: dt.datetime
    created_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="createdAt")
    ]
    updated_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="updatedAt")
    ]
    author_user_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="authorUserId")
    ] = pydantic.Field(default=None)
    """
    The user ID of the author
    """

    comment: typing.Optional[str] = pydantic.Field(default=None)
    """
    Comment on the score
    """

    metadata: typing.Any = pydantic.Field()
    """
    Metadata associated with the score
    """

    config_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="configId")
    ] = pydantic.Field(default=None)
    """
    Reference a score config on a score. When set, config and score name must be equal and value must comply to optionally defined numerical range
    """

    queue_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="queueId")
    ] = pydantic.Field(default=None)
    """
    The annotation queue referenced by the score. Indicates if score was initially created while processing annotation queue.
    """

    environment: str = pydantic.Field()
    """
    The environment from which this score originated. Can be any lowercase alphanumeric string with hyphens and underscores that does not start with 'langfuse'.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )
