# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.serialization import FieldMetadata
from .base_score_v1 import BaseScoreV1


class CategoricalScoreV1(BaseScoreV1):
    value: float = pydantic.Field()
    """
    Represents the numeric category mapping of the stringValue. If no config is linked, defaults to 0.
    """

    string_value: typing_extensions.Annotated[
        str, FieldMetadata(alias="stringValue")
    ] = pydantic.Field()
    """
    The string representation of the score value. If no config is linked, can be any string. Otherwise, must map to a config category
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )
