# This file was auto-generated by Fern from our API Definition.

import typing

from ...core import enum

T_Result = typing.TypeVar("T_Result")


class PricingTierAttributeSource(enum.StrEnum):
    MODEL_PARAMETERS = "model_parameters"
    METADATA = "metadata"

    def visit(
        self,
        model_parameters: typing.Callable[[], T_Result],
        metadata: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is PricingTierAttributeSource.MODEL_PARAMETERS:
            return model_parameters()
        if self is PricingTierAttributeSource.METADATA:
            return metadata()
