# This file was auto-generated by Fern from our API Definition.

import typing

from ...core import enum

T_Result = typing.TypeVar("T_Result")


class ScoreConfigDataType(enum.StrEnum):
    NUMERIC = "NUMERIC"
    BOOLEAN = "BOOLEAN"
    CATEGORICAL = "CATEGORICAL"

    def visit(
        self,
        numeric: typing.Callable[[], T_Result],
        boolean: typing.Callable[[], T_Result],
        categorical: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is ScoreConfigDataType.NUMERIC:
            return numeric()
        if self is ScoreConfigDataType.BOOLEAN:
            return boolean()
        if self is ScoreConfigDataType.CATEGORICAL:
            return categorical()
