# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.serialization import FieldMetadata
from .base_score import BaseScore


class TextScore(BaseScore):
    string_value: typing_extensions.Annotated[
        str, FieldMetadata(alias="stringValue")
    ] = pydantic.Field()
    """
    The text content of the score (1-500 characters)
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )
