# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import UniversalBaseModel
from ...core.serialization import FieldMetadata


class Usage(UniversalBaseModel):
    """
    (Deprecated. Use usageDetails and costDetails instead.) Standard interface for usage and cost
    """

    input: int = pydantic.Field()
    """
    Number of input units (e.g. tokens)
    """

    output: int = pydantic.Field()
    """
    Number of output units (e.g. tokens)
    """

    total: int = pydantic.Field()
    """
    Defaults to input+output if not set
    """

    unit: typing.Optional[str] = pydantic.Field(default=None)
    """
    Unit of measurement
    """

    input_cost: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="inputCost")
    ] = pydantic.Field(default=None)
    """
    USD input cost
    """

    output_cost: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="outputCost")
    ] = pydantic.Field(default=None)
    """
    USD output cost
    """

    total_cost: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="totalCost")
    ] = pydantic.Field(default=None)
    """
    USD total cost, defaults to input+output
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )
