# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ...commons.types.model_usage_unit import ModelUsageUnit
from ...commons.types.pricing_tier_input import PricingTierInput
from ...core.pydantic_utilities import UniversalBaseModel
from ...core.serialization import FieldMetadata


class CreateModelRequest(UniversalBaseModel):
    model_name: typing_extensions.Annotated[str, FieldMetadata(alias="modelName")] = (
        pydantic.Field()
    )
    """
    Name of the model definition. If multiple with the same name exist, they are applied in the following order: (1) custom over built-in, (2) newest according to startTime where model.startTime<observation.startTime
    """

    match_pattern: typing_extensions.Annotated[
        str, FieldMetadata(alias="matchPattern")
    ] = pydantic.Field()
    """
    Regex pattern which matches this model definition to generation.model. Useful in case of fine-tuned models. If you want to exact match, use `(?i)^modelname$`
    """

    start_date: typing_extensions.Annotated[
        typing.Optional[dt.datetime], FieldMetadata(alias="startDate")
    ] = pydantic.Field(default=None)
    """
    Apply only to generations which are newer than this ISO date.
    """

    unit: typing.Optional[ModelUsageUnit] = pydantic.Field(default=None)
    """
    Unit used by this model.
    """

    input_price: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="inputPrice")
    ] = pydantic.Field(default=None)
    """
    Deprecated. Use 'pricingTiers' instead. Price (USD) per input unit. Creates a default tier if pricingTiers not provided.
    """

    output_price: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="outputPrice")
    ] = pydantic.Field(default=None)
    """
    Deprecated. Use 'pricingTiers' instead. Price (USD) per output unit. Creates a default tier if pricingTiers not provided.
    """

    total_price: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="totalPrice")
    ] = pydantic.Field(default=None)
    """
    Deprecated. Use 'pricingTiers' instead. Price (USD) per total units. Cannot be set if input or output price is set. Creates a default tier if pricingTiers not provided.
    """

    pricing_tiers: typing_extensions.Annotated[
        typing.Optional[typing.List[PricingTierInput]],
        FieldMetadata(alias="pricingTiers"),
    ] = pydantic.Field(default=None)
    """
    Optional. Array of pricing tiers for this model.
    
    Use pricing tiers for all models - both those with threshold-based pricing variations and those with simple flat pricing:
    
    - For models with standard flat pricing: Create a single default tier with your prices
      (e.g., one tier with isDefault=true, priority=0, conditions=[], and your standard prices)
    
    - For models with threshold-based pricing: Create a default tier plus additional conditional tiers
      (e.g., default tier for standard usage + high-volume tier for usage above certain thresholds)
    
    Requirements:
    - Cannot be provided with flat prices (inputPrice/outputPrice/totalPrice) - use one approach or the other
    - Must include exactly one default tier with isDefault=true, priority=0, and conditions=[]
    - All tier names and priorities must be unique within the model
    - Each tier must define at least one price
    
    If omitted, you must provide flat prices instead (inputPrice/outputPrice/totalPrice),
    which will automatically create a single default tier named "Standard".
    """

    tokenizer_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="tokenizerId")
    ] = pydantic.Field(default=None)
    """
    Optional. Tokenizer to be applied to observations which match to this model. See docs for more details.
    """

    tokenizer_config: typing_extensions.Annotated[
        typing.Optional[typing.Any], FieldMetadata(alias="tokenizerConfig")
    ] = pydantic.Field(default=None)
    """
    Optional. Configuration for the selected tokenizer. Needs to be JSON. See docs for more details.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )
