# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .create_skill_version_request import CreateSkillVersionRequest
    from .delete_skill_version_response import DeleteSkillVersionResponse
    from .skill_file import SkillFile
    from .skill_file_content_response import SkillFileContentResponse
    from .skill_list_pagination import SkillListPagination
    from .skill_meta import SkillMeta
    from .skill_meta_list_response import SkillMetaListResponse
    from .skill_version import SkillVersion
    from .skill_version_file_create_input import SkillVersionFileCreateInput
    from .skill_version_file_input import SkillVersionFileInput
    from .skill_version_file_reference import SkillVersionFileReference
    from .update_skill_labels_request import UpdateSkillLabelsRequest
    from .update_skill_request import UpdateSkillRequest
_dynamic_imports: typing.Dict[str, str] = {
    "CreateSkillVersionRequest": ".create_skill_version_request",
    "DeleteSkillVersionResponse": ".delete_skill_version_response",
    "SkillFile": ".skill_file",
    "SkillFileContentResponse": ".skill_file_content_response",
    "SkillListPagination": ".skill_list_pagination",
    "SkillMeta": ".skill_meta",
    "SkillMetaListResponse": ".skill_meta_list_response",
    "SkillVersion": ".skill_version",
    "SkillVersionFileCreateInput": ".skill_version_file_create_input",
    "SkillVersionFileInput": ".skill_version_file_input",
    "SkillVersionFileReference": ".skill_version_file_reference",
    "UpdateSkillLabelsRequest": ".update_skill_labels_request",
    "UpdateSkillRequest": ".update_skill_request",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(
            f"No {attr_name} found in _dynamic_imports for module name -> {__name__}"
        )
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(
            f"Failed to import {attr_name} from {module_name}: {e}"
        ) from e
    except AttributeError as e:
        raise AttributeError(
            f"Failed to get {attr_name} from {module_name}: {e}"
        ) from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "CreateSkillVersionRequest",
    "DeleteSkillVersionResponse",
    "SkillFile",
    "SkillFileContentResponse",
    "SkillListPagination",
    "SkillMeta",
    "SkillMetaListResponse",
    "SkillVersion",
    "SkillVersionFileCreateInput",
    "SkillVersionFileInput",
    "SkillVersionFileReference",
    "UpdateSkillLabelsRequest",
    "UpdateSkillRequest",
]
