# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import UniversalBaseModel
from ....core.serialization import FieldMetadata
from .skill_file import SkillFile


class SkillVersion(UniversalBaseModel):
    id: str
    created_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="createdAt")
    ]
    updated_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="updatedAt")
    ]
    project_id: typing_extensions.Annotated[str, FieldMetadata(alias="projectId")]
    created_by: typing_extensions.Annotated[str, FieldMetadata(alias="createdBy")]
    name: str
    description: str
    frontmatter: typing.Any
    version: int
    tags: typing.List[str]
    labels: typing.List[str]
    commit_message: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="commitMessage")
    ] = None
    files: typing.List[SkillFile]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )
