# This file was auto-generated by Fern from our API Definition.

from .base_score import BaseScore
import typing
import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2


class CategoricalScore(BaseScore):
    value: typing.Optional[float] = pydantic.Field(default=None)
    """
    Only defined if a config is linked. Represents the numeric category mapping of the stringValue
    """

    string_value: str = pydantic.Field(alias="stringValue")
    """
    The string representation of the score value. If no config is linked, can be any string. Otherwise, must map to a config category
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
