# This file was auto-generated by Fern from our API Definition.

import typing

ModelUsageUnit = typing.Union[
    typing.Literal[
        "CHARACTERS", "TOKENS", "MILLISECONDS", "SECONDS", "IMAGES", "REQUESTS"
    ],
    typing.Any,
]
