# This file was auto-generated by Fern from our API Definition.

import typing

from .boolean_score_v_1 import BooleanScoreV1
from .categorical_score_v_1 import CategoricalScoreV1
from .numeric_score_v_1 import NumericScoreV1

ScoreV1 = typing.Union[NumericScoreV1, CategoricalScoreV1, BooleanScoreV1]
