# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import UniversalBaseModel
from ...core.serialization import FieldMetadata
from .api_key_summary import ApiKeySummary


class ApiKeyList(UniversalBaseModel):
    """
    List of API keys for a project
    """

    api_keys: typing_extensions.Annotated[
        typing.List[ApiKeySummary], FieldMetadata(alias="apiKeys")
    ]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )
