# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import UniversalBaseModel


class DashboardWidgetFilter(UniversalBaseModel):
    """
    A dashboard widget filter in Langfuse filter-state shape.

    Filter shapes depend on `type`, for example string filters use a string `value`,
    option filters use a list of strings, and object filters include `key`.
    """

    column: str
    operator: str
    type: str
    value: typing.Optional[typing.Any] = None
    key: typing.Optional[str] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )
