# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import UniversalBaseModel
from ....core.serialization import FieldMetadata
from .dashboard_widget_chart_type import DashboardWidgetChartType
from .dashboard_widget_default_sort import DashboardWidgetDefaultSort


class DashboardWidgetChartConfigInput(UniversalBaseModel):
    """
    Input-side chart config. `type` is optional and defaults to the
    widget's `chartType`; when given it must match.
    """

    type: typing.Optional[DashboardWidgetChartType] = None
    row_limit: typing.Optional[int] = None
    show_value_labels: typing.Optional[bool] = None
    bins: typing.Optional[int] = None
    default_sort: typing_extensions.Annotated[
        typing.Optional[DashboardWidgetDefaultSort], FieldMetadata(alias="defaultSort")
    ] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )
