# This file was auto-generated by Fern from our API Definition.

import typing

from ....core import enum

T_Result = typing.TypeVar("T_Result")


class DashboardWidgetChartType(enum.StrEnum):
    LINE_TIME_SERIES = "LINE_TIME_SERIES"
    AREA_TIME_SERIES = "AREA_TIME_SERIES"
    BAR_TIME_SERIES = "BAR_TIME_SERIES"
    HORIZONTAL_BAR = "HORIZONTAL_BAR"
    VERTICAL_BAR = "VERTICAL_BAR"
    PIE = "PIE"
    NUMBER = "NUMBER"
    HISTOGRAM = "HISTOGRAM"
    PIVOT_TABLE = "PIVOT_TABLE"

    def visit(
        self,
        line_time_series: typing.Callable[[], T_Result],
        area_time_series: typing.Callable[[], T_Result],
        bar_time_series: typing.Callable[[], T_Result],
        horizontal_bar: typing.Callable[[], T_Result],
        vertical_bar: typing.Callable[[], T_Result],
        pie: typing.Callable[[], T_Result],
        number: typing.Callable[[], T_Result],
        histogram: typing.Callable[[], T_Result],
        pivot_table: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is DashboardWidgetChartType.LINE_TIME_SERIES:
            return line_time_series()
        if self is DashboardWidgetChartType.AREA_TIME_SERIES:
            return area_time_series()
        if self is DashboardWidgetChartType.BAR_TIME_SERIES:
            return bar_time_series()
        if self is DashboardWidgetChartType.HORIZONTAL_BAR:
            return horizontal_bar()
        if self is DashboardWidgetChartType.VERTICAL_BAR:
            return vertical_bar()
        if self is DashboardWidgetChartType.PIE:
            return pie()
        if self is DashboardWidgetChartType.NUMBER:
            return number()
        if self is DashboardWidgetChartType.HISTOGRAM:
            return histogram()
        if self is DashboardWidgetChartType.PIVOT_TABLE:
            return pivot_table()
