# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import UniversalBaseModel


class DashboardWidgetFilter(UniversalBaseModel):
    """
    A filter in Langfuse filter-state shape. The `value` shape and the
    allowed operators depend on `type`:

    | `type` | `value` | operators |
    |---|---|---|
    | `string` | string | `=`, `contains`, `does not contain`, `starts with`, `ends with` |
    | `number` | number | `=`, `>`, `<`, `>=`, `<=` |
    | `datetime` | ISO datetime string | `>`, `<`, `>=`, `<=` |
    | `boolean` | boolean | `=`, `<>` |
    | `null` | `""` | `is null`, `is not null` |
    | `stringOptions` | list of strings | `any of`, `none of` |
    | `arrayOptions` | list of strings | `any of`, `none of`, `all of` |
    | `categoryOptions` | list of strings (requires `key`) | `any of`, `none of` |
    | `stringObject` | string (requires `key`, e.g. a metadata key) | same as `string` |
    | `numberObject` | number (requires `key`, e.g. a score name) | same as `number` |
    | `booleanObject` | boolean (requires `key`) | `=`, `<>` |
    """

    column: str
    operator: str
    type: str
    value: typing.Optional[typing.Any] = None
    key: typing.Optional[str] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )
