# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import UniversalBaseModel


class Creator(UniversalBaseModel):
    """
    User who created the resource, or `null` when no user can be resolved.
    """

    id: str = pydantic.Field()
    """
    User identifier.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    User name, or `null` when unavailable.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )
