# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import UniversalBaseModel


class DeletedEvaluator(UniversalBaseModel):
    """
    Confirmation returned after successful evaluator deletion.
    """

    id: str = pydantic.Field()
    """
    Identifier of the deleted evaluator.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )
