# This file was auto-generated by Fern from our API Definition.

import typing

from .chat_message import ChatMessage
from .placeholder_message import PlaceholderMessage

ChatMessageWithPlaceholders = typing.Union[ChatMessage, PlaceholderMessage]
