# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import UniversalBaseModel
from .placeholder_message_type import PlaceholderMessageType


class PlaceholderMessage(UniversalBaseModel):
    name: str
    type: typing.Optional[PlaceholderMessageType] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )
