# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import UniversalBaseModel
from .resource_meta import ResourceMeta


class SchemaResource(UniversalBaseModel):
    id: str
    name: str
    description: str
    attributes: typing.List[typing.Any]
    meta: ResourceMeta

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )
