# This file was auto-generated by Fern from our API Definition.

import datetime as dt


def serialize_datetime(v: dt.datetime) -> str:
    """
    Serialize a datetime including timezone info.

    Assumes naive datetime (without tzinfo) is UTC, as Langfuse infrastructure
    expects all timestamps in UTC. This prevents timestamp inconsistencies that
    cause duplicate trace records in ClickHouse when the SDK runs in non-UTC timezones.

    UTC datetimes end in "Z" while all other timezones are represented as offset from UTC, e.g. +05:00.
    """

    def _serialize_zoned_datetime(v: dt.datetime) -> str:
        if v.tzinfo is not None and v.tzinfo.tzname(None) == dt.timezone.utc.tzname(
            None
        ):
            # UTC is a special case where we use "Z" at the end instead of "+00:00"
            return v.isoformat().replace("+00:00", "Z")
        else:
            # Delegate to the typical +/- offset format
            return v.isoformat()

    if v.tzinfo is not None:
        return _serialize_zoned_datetime(v)
    else:
        # Assume naive datetime is UTC (Langfuse standard)
        # This fixes duplicate trace records caused by timezone inconsistencies
        utc_dt = v.replace(tzinfo=dt.timezone.utc)
        return _serialize_zoned_datetime(utc_dt)
