# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...commons.types.observations_view import ObservationsView
from ...core.pydantic_utilities import UniversalBaseModel
from ...utils.pagination.types.meta_response import MetaResponse


class ObservationsViews(UniversalBaseModel):
    data: typing.List[ObservationsView]
    meta: MetaResponse

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )
