# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        BaseScoreV3,
        BooleanScoreV3,
        CategoricalScoreV3,
        CorrectionScoreV3,
        GetScoresMeta,
        GetScoresResponse,
        NumericScoreV3,
        ScoreSubject,
        ScoreSubjectExperiment,
        ScoreSubjectObservation,
        ScoreSubjectSession,
        ScoreSubjectTrace,
        ScoreSubject_Experiment,
        ScoreSubject_Observation,
        ScoreSubject_Session,
        ScoreSubject_Trace,
        ScoreV3,
        ScoreV3_Boolean,
        ScoreV3_Categorical,
        ScoreV3_Correction,
        ScoreV3_Numeric,
        ScoreV3_Text,
        TextScoreV3,
    )
_dynamic_imports: typing.Dict[str, str] = {
    "BaseScoreV3": ".types",
    "BooleanScoreV3": ".types",
    "CategoricalScoreV3": ".types",
    "CorrectionScoreV3": ".types",
    "GetScoresMeta": ".types",
    "GetScoresResponse": ".types",
    "NumericScoreV3": ".types",
    "ScoreSubject": ".types",
    "ScoreSubjectExperiment": ".types",
    "ScoreSubjectObservation": ".types",
    "ScoreSubjectSession": ".types",
    "ScoreSubjectTrace": ".types",
    "ScoreSubject_Experiment": ".types",
    "ScoreSubject_Observation": ".types",
    "ScoreSubject_Session": ".types",
    "ScoreSubject_Trace": ".types",
    "ScoreV3": ".types",
    "ScoreV3_Boolean": ".types",
    "ScoreV3_Categorical": ".types",
    "ScoreV3_Correction": ".types",
    "ScoreV3_Numeric": ".types",
    "ScoreV3_Text": ".types",
    "TextScoreV3": ".types",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(
            f"No {attr_name} found in _dynamic_imports for module name -> {__name__}"
        )
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(
            f"Failed to import {attr_name} from {module_name}: {e}"
        ) from e
    except AttributeError as e:
        raise AttributeError(
            f"Failed to get {attr_name} from {module_name}: {e}"
        ) from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "BaseScoreV3",
    "BooleanScoreV3",
    "CategoricalScoreV3",
    "CorrectionScoreV3",
    "GetScoresMeta",
    "GetScoresResponse",
    "NumericScoreV3",
    "ScoreSubject",
    "ScoreSubjectExperiment",
    "ScoreSubjectObservation",
    "ScoreSubjectSession",
    "ScoreSubjectTrace",
    "ScoreSubject_Experiment",
    "ScoreSubject_Observation",
    "ScoreSubject_Session",
    "ScoreSubject_Trace",
    "ScoreV3",
    "ScoreV3_Boolean",
    "ScoreV3_Categorical",
    "ScoreV3_Correction",
    "ScoreV3_Numeric",
    "ScoreV3_Text",
    "TextScoreV3",
]
