# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import UniversalBaseModel
from ....core.serialization import FieldMetadata
from ...commons.types.code_evaluator_source_code_language import (
    CodeEvaluatorSourceCodeLanguage,
)
from ...commons.types.evaluator_model_config import EvaluatorModelConfig
from ...commons.types.evaluator_output_definition import EvaluatorOutputDefinition


class CreateEvaluatorRequest_LlmAsJudge(UniversalBaseModel):
    """
    Request body for creating an evaluator.

    If the same `name` already exists in your project, Langfuse creates the next version and returns it.
    Existing evaluation rules in the same project are then moved to that new latest version automatically.
    If `type` is omitted, Langfuse defaults it to `llm_as_judge` for backwards compatibility.
    """

    type: typing.Literal["llm_as_judge"] = "llm_as_judge"
    name: str
    prompt: str
    output_definition: typing_extensions.Annotated[
        EvaluatorOutputDefinition, FieldMetadata(alias="outputDefinition")
    ]
    model_config_: typing_extensions.Annotated[
        typing.Optional[EvaluatorModelConfig], FieldMetadata(alias="modelConfig")
    ] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )


class CreateEvaluatorRequest_Code(UniversalBaseModel):
    """
    Request body for creating an evaluator.

    If the same `name` already exists in your project, Langfuse creates the next version and returns it.
    Existing evaluation rules in the same project are then moved to that new latest version automatically.
    If `type` is omitted, Langfuse defaults it to `llm_as_judge` for backwards compatibility.
    """

    type: typing.Literal["code"] = "code"
    name: str
    source_code: typing_extensions.Annotated[str, FieldMetadata(alias="sourceCode")]
    source_code_language: typing_extensions.Annotated[
        CodeEvaluatorSourceCodeLanguage, FieldMetadata(alias="sourceCodeLanguage")
    ]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )


CreateEvaluatorRequest = typing_extensions.Annotated[
    typing.Union[CreateEvaluatorRequest_LlmAsJudge, CreateEvaluatorRequest_Code],
    pydantic.Field(discriminator="type"),
]
