# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import UniversalBaseModel
from ....core.serialization import FieldMetadata
from ...commons.types.evaluator_model_config import EvaluatorModelConfig
from ...commons.types.evaluator_output_definition import EvaluatorOutputDefinition


class CreateEvaluatorRequest(UniversalBaseModel):
    """
    Request body for creating an evaluator.

    If the same `name` already exists in your project, Langfuse creates the next version and returns it.
    Existing evaluation rules in the same project are then moved to that new latest version automatically.
    """

    name: str = pydantic.Field()
    """
    Evaluator name within the authenticated project.
    """

    prompt: str = pydantic.Field()
    """
    Prompt template used by the evaluator.
    """

    output_definition: typing_extensions.Annotated[
        EvaluatorOutputDefinition, FieldMetadata(alias="outputDefinition")
    ] = pydantic.Field()
    """
    Structured output schema the evaluator must return.
    
    Always send `dataType`.
    Do not send `version`; it is an internal storage detail and not part of the public request contract.
    """

    model_config_: typing_extensions.Annotated[
        typing.Optional[EvaluatorModelConfig], FieldMetadata(alias="modelConfig")
    ] = pydantic.Field(default=None)
    """
    Optional explicit model configuration. Omit or set to `null` to use the project default evaluation model.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )
