# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import UniversalBaseModel


class DeleteEvaluatorResponse(UniversalBaseModel):
    """
    Confirmation response returned after successful deletion.
    """

    message: str = pydantic.Field()
    """
    Always `Evaluator successfully deleted`.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )
