# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import UniversalBaseModel
from ....utils.pagination.types.meta_response import MetaResponse
from .evaluator import Evaluator


class Evaluators(UniversalBaseModel):
    data: typing.List[Evaluator]
    meta: MetaResponse

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )
