# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ....core.serialization import FieldMetadata
from ...commons.types.evaluator_model_config import EvaluatorModelConfig
from ...commons.types.public_evaluator_output_definition import (
    PublicEvaluatorOutputDefinition,
)
from .evaluator_base import EvaluatorBase


class LlmAsJudgeEvaluator(EvaluatorBase):
    prompt: str = pydantic.Field()
    """
    Prompt template used during evaluation.
    """

    output_definition: typing_extensions.Annotated[
        PublicEvaluatorOutputDefinition, FieldMetadata(alias="outputDefinition")
    ] = pydantic.Field()
    """
    Structured output schema returned by this evaluator.
    
    Responses always include `dataType` and omit the internal output-definition `version`.
    Use `dataType` to decide how future scores should be interpreted.
    """

    model_config_: typing_extensions.Annotated[
        typing.Optional[EvaluatorModelConfig], FieldMetadata(alias="modelConfig")
    ] = pydantic.Field(default=None)
    """
    Explicit model configuration, or `null` when the project default evaluation model is used.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )
