# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .create_score_batch_error import CreateScoreBatchError
    from .create_score_batch_request import CreateScoreBatchRequest
    from .create_score_batch_response import CreateScoreBatchResponse
    from .create_score_batch_results import CreateScoreBatchResults
    from .create_score_request import CreateScoreRequest
    from .create_score_response import CreateScoreResponse
    from .create_score_source import CreateScoreSource
    from .create_scores_request import CreateScoresRequest
    from .create_scores_response import CreateScoresResponse
_dynamic_imports: typing.Dict[str, str] = {
    "CreateScoreBatchError": ".create_score_batch_error",
    "CreateScoreBatchRequest": ".create_score_batch_request",
    "CreateScoreBatchResponse": ".create_score_batch_response",
    "CreateScoreBatchResults": ".create_score_batch_results",
    "CreateScoreRequest": ".create_score_request",
    "CreateScoreResponse": ".create_score_response",
    "CreateScoreSource": ".create_score_source",
    "CreateScoresRequest": ".create_scores_request",
    "CreateScoresResponse": ".create_scores_response",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(
            f"No {attr_name} found in _dynamic_imports for module name -> {__name__}"
        )
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(
            f"Failed to import {attr_name} from {module_name}: {e}"
        ) from e
    except AttributeError as e:
        raise AttributeError(
            f"Failed to get {attr_name} from {module_name}: {e}"
        ) from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "CreateScoreBatchError",
    "CreateScoreBatchRequest",
    "CreateScoreBatchResponse",
    "CreateScoreBatchResults",
    "CreateScoreRequest",
    "CreateScoreResponse",
    "CreateScoreSource",
    "CreateScoresRequest",
    "CreateScoresResponse",
]
