# This file was auto-generated by Fern from our API Definition.

import typing

from .create_score_batch_request import CreateScoreBatchRequest
from .create_score_request import CreateScoreRequest

CreateScoresRequest = typing.Union[CreateScoreRequest, CreateScoreBatchRequest]
