# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import UniversalBaseModel


class GetScoresMeta(UniversalBaseModel):
    limit: int
    cursor: typing.Optional[str] = pydantic.Field(default=None)
    """
    URL-safe base64 (base64url) cursor for the next page. Absent when there are no more results.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )
