# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import datetime as dt
import typing

import pydantic
import typing_extensions
from ...commons.types.score_source import ScoreSource
from ...core.pydantic_utilities import UniversalBaseModel
from ...core.serialization import FieldMetadata
from .score_subject import ScoreSubject


class ScoreV3_Numeric(UniversalBaseModel):
    data_type: typing_extensions.Annotated[
        typing.Literal["NUMERIC"], FieldMetadata(alias="dataType")
    ] = "NUMERIC"
    value: float
    id: str
    project_id: typing_extensions.Annotated[str, FieldMetadata(alias="projectId")]
    name: str
    source: ScoreSource
    timestamp: dt.datetime
    environment: str
    created_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="createdAt")
    ]
    updated_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="updatedAt")
    ]
    comment: typing.Optional[str] = None
    config_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="configId")
    ] = None
    metadata: typing.Optional[typing.Dict[str, typing.Any]] = None
    author_user_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="authorUserId")
    ] = None
    queue_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="queueId")
    ] = None
    subject: typing.Optional[ScoreSubject] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )


class ScoreV3_Boolean(UniversalBaseModel):
    data_type: typing_extensions.Annotated[
        typing.Literal["BOOLEAN"], FieldMetadata(alias="dataType")
    ] = "BOOLEAN"
    value: bool
    id: str
    project_id: typing_extensions.Annotated[str, FieldMetadata(alias="projectId")]
    name: str
    source: ScoreSource
    timestamp: dt.datetime
    environment: str
    created_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="createdAt")
    ]
    updated_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="updatedAt")
    ]
    comment: typing.Optional[str] = None
    config_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="configId")
    ] = None
    metadata: typing.Optional[typing.Dict[str, typing.Any]] = None
    author_user_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="authorUserId")
    ] = None
    queue_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="queueId")
    ] = None
    subject: typing.Optional[ScoreSubject] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )


class ScoreV3_Categorical(UniversalBaseModel):
    data_type: typing_extensions.Annotated[
        typing.Literal["CATEGORICAL"], FieldMetadata(alias="dataType")
    ] = "CATEGORICAL"
    value: str
    id: str
    project_id: typing_extensions.Annotated[str, FieldMetadata(alias="projectId")]
    name: str
    source: ScoreSource
    timestamp: dt.datetime
    environment: str
    created_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="createdAt")
    ]
    updated_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="updatedAt")
    ]
    comment: typing.Optional[str] = None
    config_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="configId")
    ] = None
    metadata: typing.Optional[typing.Dict[str, typing.Any]] = None
    author_user_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="authorUserId")
    ] = None
    queue_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="queueId")
    ] = None
    subject: typing.Optional[ScoreSubject] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )


class ScoreV3_Text(UniversalBaseModel):
    data_type: typing_extensions.Annotated[
        typing.Literal["TEXT"], FieldMetadata(alias="dataType")
    ] = "TEXT"
    value: str
    id: str
    project_id: typing_extensions.Annotated[str, FieldMetadata(alias="projectId")]
    name: str
    source: ScoreSource
    timestamp: dt.datetime
    environment: str
    created_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="createdAt")
    ]
    updated_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="updatedAt")
    ]
    comment: typing.Optional[str] = None
    config_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="configId")
    ] = None
    metadata: typing.Optional[typing.Dict[str, typing.Any]] = None
    author_user_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="authorUserId")
    ] = None
    queue_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="queueId")
    ] = None
    subject: typing.Optional[ScoreSubject] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )


class ScoreV3_Correction(UniversalBaseModel):
    data_type: typing_extensions.Annotated[
        typing.Literal["CORRECTION"], FieldMetadata(alias="dataType")
    ] = "CORRECTION"
    value: str
    id: str
    project_id: typing_extensions.Annotated[str, FieldMetadata(alias="projectId")]
    name: str
    source: ScoreSource
    timestamp: dt.datetime
    environment: str
    created_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="createdAt")
    ]
    updated_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="updatedAt")
    ]
    comment: typing.Optional[str] = None
    config_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="configId")
    ] = None
    metadata: typing.Optional[typing.Dict[str, typing.Any]] = None
    author_user_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="authorUserId")
    ] = None
    queue_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="queueId")
    ] = None
    subject: typing.Optional[ScoreSubject] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )


ScoreV3 = typing_extensions.Annotated[
    typing.Union[
        ScoreV3_Numeric,
        ScoreV3_Boolean,
        ScoreV3_Categorical,
        ScoreV3_Text,
        ScoreV3_Correction,
    ],
    pydantic.Field(discriminator="data_type"),
]
