# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import UniversalBaseModel
from ...core.serialization import FieldMetadata


class OrganizationApiKey(UniversalBaseModel):
    id: str
    created_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="createdAt")
    ]
    expires_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime], FieldMetadata(alias="expiresAt")
    ] = pydantic.Field(default=None)
    """
    Expiration timestamp. Null if the key does not expire.
    """

    last_used_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime], FieldMetadata(alias="lastUsedAt")
    ] = None
    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Name of the API key. Contains the same value as note; null if no name was provided.
    """

    note: typing.Optional[str] = pydantic.Field(default=None)
    """
    Deprecated alias for name. Contains the same value as name.
    """

    public_key: typing_extensions.Annotated[str, FieldMetadata(alias="publicKey")]
    display_secret_key: typing_extensions.Annotated[
        str, FieldMetadata(alias="displaySecretKey")
    ]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )
