#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
import os
import shutil
import sys
from pathlib import Path
from typing import Any


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--repo-root", type=Path)
    return parser.parse_args()


def load_config(repo_root: Path) -> dict[str, Any]:
    source_path = repo_root / ".agents" / "config.json"
    return json.loads(source_path.read_text(encoding="utf-8"))


def sort_object(value: dict[str, Any]) -> dict[str, Any]:
    return {key: value[key] for key in sorted(value)}


def format_shared_json_config(servers: dict[str, Any]) -> str:
    mcp_servers: dict[str, Any] = {}

    for name, server in sort_object(servers).items():
        if server["transport"] == "stdio":
            mcp_servers[name] = {
                "command": server["command"],
                "args": server.get("args", []),
                **({"env": server["env"]} if server.get("env") else {}),
            }
        else:
            mcp_servers[name] = {
                "type": "http",
                "url": server["url"],
                **({"headers": server["headers"]} if server.get("headers") else {}),
            }

    return json.dumps({"mcpServers": mcp_servers}, indent=2) + "\n"


def format_vscode_config(servers: dict[str, Any]) -> str:
    mcp_servers: dict[str, Any] = {}

    for name, server in sort_object(servers).items():
        if server["transport"] == "stdio":
            mcp_servers[name] = {
                "type": "stdio",
                "command": server["command"],
                "args": server.get("args", []),
                **({"env": server["env"]} if server.get("env") else {}),
            }
        else:
            mcp_servers[name] = {
                "type": "http",
                "url": server["url"],
                **({"headers": server["headers"]} if server.get("headers") else {}),
            }

    return json.dumps({"servers": mcp_servers}, indent=2) + "\n"


def format_codex_toml(servers: dict[str, Any]) -> str:
    lines: list[str] = []

    for name, server in sort_object(servers).items():
        lines.append(f"[mcp_servers.{name}]")

        if server["transport"] == "stdio":
            lines.append(f"command = {json.dumps(server['command'])}")

            args = server.get("args", [])
            if args:
                lines.append("args = [")
                for arg in args:
                    lines.append(f"  {json.dumps(arg)},")
                lines.append("]")
            else:
                lines.append("args = []")

            if server.get("env"):
                lines.append(f"[mcp_servers.{name}.env]")
                for env_name, env_value in sort_object(server["env"]).items():
                    lines.append(f"{env_name} = {json.dumps(env_value)}")
        else:
            lines.append(f"url = {json.dumps(server['url'])}")
            if server.get("headers"):
                lines.append(f"[mcp_servers.{name}.headers]")
                for header_name, header_value in sort_object(server["headers"]).items():
                    lines.append(
                        f"{json.dumps(header_name)} = {json.dumps(header_value)}"
                    )

        lines.append("")

    return "\n".join(lines)


def format_claude_settings(config: dict[str, Any]) -> str:
    return json.dumps(config["claude"]["settings"], indent=2) + "\n"


def format_cursor_environment(config: dict[str, Any]) -> str:
    return (
        json.dumps(
            {
                "agentCanUpdateSnapshot": config["cursor"]["environment"][
                    "agentCanUpdateSnapshot"
                ],
                "install": config["shared"]["setupScript"],
                "terminals": [
                    {
                        "name": "Development Terminal",
                        "command": config["shared"]["devCommand"],
                        "description": config["shared"]["devTerminalDescription"],
                    }
                ],
            },
            indent=2,
        )
        + "\n"
    )


def format_codex_environment_toml(config: dict[str, Any]) -> str:
    lines = [
        "# THIS IS AUTOGENERATED. DO NOT EDIT MANUALLY",
        f"version = {config['codex']['environment']['version']}",
        f"name = {json.dumps(config['codex']['environment']['name'])}",
        "",
        "[setup]",
        f"script = {json.dumps(config['shared']['setupScript'])}",
        "",
    ]

    return "\n".join(lines)


def write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def remove_path(path: Path) -> None:
    if not path.exists() and not path.is_symlink():
        return
    if path.is_dir() and not path.is_symlink():
        shutil.rmtree(path)
    else:
        path.unlink()


def expected_symlink_target(path: Path, target: Path) -> Path:
    return Path(os.path.relpath(target, start=path.parent))


def is_matching_symlink(path: Path, target: Path) -> bool:
    if not path.is_symlink():
        return False
    return Path(os.readlink(path)) == expected_symlink_target(path, target)


def is_within_repo(path: Path, repo_root: Path) -> bool:
    try:
        path.resolve().relative_to(repo_root.resolve())
        return True
    except ValueError:
        return False


def find_unexpected_children(path: Path, expected_children: set[str]) -> list[Path]:
    if not path.exists():
        return []
    return [child for child in path.iterdir() if child.name not in expected_children]


def print_error(message: str) -> None:
    print(message, file=sys.stderr)


def is_writable(path: Path) -> bool:
    target = path if path.exists() else path.parent
    return os.access(target, os.W_OK)


def sync_file_outputs(
    file_outputs: list[dict[str, Any]], check_mode: bool
) -> tuple[bool, list[str]]:
    has_mismatch = False
    warnings: list[str] = []

    for output in file_outputs:
        path: Path = output["path"]
        content: str = output["content"]
        optional: bool = output.get("optional", False)

        if check_mode:
            if optional and not is_writable(path):
                warnings.append(f"Skipping optional config check: {path}")
                continue
            try:
                current = path.read_text(encoding="utf-8")
            except FileNotFoundError:
                if optional:
                    warnings.append(f"Skipping optional config check: {path}")
                    continue
                has_mismatch = True
                print_error(
                    f'Missing generated config: {path}. Run "python3 .agents/scripts/sync-agent-shims.py".'
                )
                continue

            if current != content:
                has_mismatch = True
                print_error(f"Out of sync: {path}")
            continue

        try:
            write_text(path, content)
            print(f"Updated {path}")
        except OSError:
            if optional:
                warnings.append(f"Skipping optional config generation: {path}")
                continue
            raise

    return has_mismatch, warnings


def sync_symlink_outputs(
    symlink_outputs: list[dict[str, Path]], check_mode: bool
) -> bool:
    has_mismatch = False

    for output in symlink_outputs:
        path = output["path"]
        target = output["target"]

        if check_mode:
            if not is_matching_symlink(path, target):
                has_mismatch = True
                print_error(
                    f'Out of sync symlink: {path}. Run "python3 .agents/scripts/sync-agent-shims.py".'
                )
            continue

        path.parent.mkdir(parents=True, exist_ok=True)

        if is_matching_symlink(path, target):
            continue

        remove_path(path)
        path.symlink_to(
            expected_symlink_target(path, target), target_is_directory=target.is_dir()
        )
        print(f"Linked {path}")

    return has_mismatch


def sync_managed_directories(
    managed_directories: list[dict[str, Any]], repo_root: Path, check_mode: bool
) -> bool:
    has_mismatch = False

    for directory in managed_directories:
        path: Path = directory["path"]
        expected_children: set[str] = directory["expected_children"]

        if path.is_symlink():
            message = f"Managed generated shim directory must not be a symlink: {path}"
            if check_mode:
                has_mismatch = True
                print_error(message)
                continue
            raise RuntimeError(message)

        if path.exists() and not is_within_repo(path, repo_root):
            message = (
                f"Managed generated shim directory resolves outside the repository: {path}"
            )
            if check_mode:
                has_mismatch = True
                print_error(message)
                continue
            raise RuntimeError(message)

        unexpected_children = find_unexpected_children(path, expected_children)

        if not unexpected_children:
            continue

        if check_mode:
            has_mismatch = True
            for child in unexpected_children:
                print_error(f"Unexpected generated shim: {child}")
            continue

        for child in unexpected_children:
            remove_path(child)
            print(f"Removed stale generated shim {child}")

    return has_mismatch


def main() -> int:
    args = parse_args()
    repo_root = (
        args.repo_root.resolve()
        if args.repo_root is not None
        else Path(__file__).resolve().parents[2]
    )

    config = load_config(repo_root)
    servers = config["mcpServers"]
    check_mode = args.check

    file_outputs = [
        {
            "path": repo_root / ".claude" / "settings.json",
            "content": format_claude_settings(config),
        },
        {
            "path": repo_root / ".mcp.json",
            "content": format_shared_json_config(servers),
        },
        {
            "path": repo_root / ".codex" / "environments" / "environment.toml",
            "content": format_codex_environment_toml(config),
            "optional": True,
        },
        {
            "path": repo_root / ".cursor" / "mcp.json",
            "content": format_shared_json_config(servers),
        },
        {
            "path": repo_root / ".cursor" / "environment.json",
            "content": format_cursor_environment(config),
        },
        {
            "path": repo_root / ".vscode" / "mcp.json",
            "content": format_vscode_config(servers),
        },
        {
            "path": repo_root / ".codex" / "config.toml",
            "content": format_codex_toml(servers),
            "optional": True,
        },
    ]

    skills_root = repo_root / ".agents" / "skills"
    shared_skill_names = sorted(
        entry.name
        for entry in (skills_root.iterdir() if skills_root.exists() else [])
        if entry.is_dir() and (entry / "SKILL.md").exists()
    )

    symlink_outputs = [
        {
            "path": repo_root / "AGENTS.md",
            "target": repo_root / ".agents" / "AGENTS.md",
        },
        {
            "path": repo_root / "CLAUDE.md",
            "target": repo_root / "AGENTS.md",
        },
        *[
            {
                "path": repo_root / ".claude" / "skills" / name,
                "target": skills_root / name,
            }
            for name in shared_skill_names
        ],
    ]

    managed_directories = [
        {
            "path": repo_root / ".claude" / "skills",
            "expected_children": set(shared_skill_names),
        }
    ]

    has_mismatch, warnings = sync_file_outputs(file_outputs, check_mode)
    for warning in warnings:
        print(warning)

    has_mismatch = sync_symlink_outputs(symlink_outputs, check_mode) or has_mismatch
    has_mismatch = (
        sync_managed_directories(managed_directories, repo_root, check_mode)
        or has_mismatch
    )

    return 1 if check_mode and has_mismatch else 0


if __name__ == "__main__":
    raise SystemExit(main())
