# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from .base_event import BaseEvent
from .observation_body import ObservationBody


class CreateObservationEvent(BaseEvent):
    body: ObservationBody

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )
