# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import UniversalBaseModel


class OpenAiCompletionUsageSchema(UniversalBaseModel):
    """
    OpenAI Usage schema from (Chat-)Completion APIs
    """

    prompt_tokens: int
    completion_tokens: int
    total_tokens: int
    prompt_tokens_details: typing.Optional[typing.Dict[str, typing.Optional[int]]] = (
        None
    )
    completion_tokens_details: typing.Optional[
        typing.Dict[str, typing.Optional[int]]
    ] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )
