# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ...commons.types.observation_level import ObservationLevel
from ...core.pydantic_utilities import UniversalBaseModel
from ...core.serialization import FieldMetadata


class OptionalObservationBody(UniversalBaseModel):
    trace_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="traceId")
    ] = None
    name: typing.Optional[str] = None
    start_time: typing_extensions.Annotated[
        typing.Optional[dt.datetime], FieldMetadata(alias="startTime")
    ] = None
    metadata: typing.Optional[typing.Any] = None
    input: typing.Optional[typing.Any] = None
    output: typing.Optional[typing.Any] = None
    level: typing.Optional[ObservationLevel] = None
    status_message: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="statusMessage")
    ] = None
    parent_observation_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="parentObservationId")
    ] = None
    version: typing.Optional[str] = None
    environment: typing.Optional[str] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )
