# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from .base_event import BaseEvent
from .update_generation_body import UpdateGenerationBody


class UpdateGenerationEvent(BaseEvent):
    body: UpdateGenerationBody

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )
