# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from .optional_observation_body import OptionalObservationBody


class UpdateEventBody(OptionalObservationBody):
    id: str

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )
