# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import UniversalBaseModel


class SubmitFeedbackResponse(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    Correlation ID for the submitted feedback.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )
