# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import UniversalBaseModel


class PublicApiValidationIssue(UniversalBaseModel):
    """
    A validation issue returned for malformed request bodies or query parameters.
    """

    code: str
    message: str
    path: typing.List[typing.Any]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )
