# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import UniversalBaseModel
from ....core.serialization import FieldMetadata
from .public_api_validation_issue import PublicApiValidationIssue


class PublicApiErrorDetails(UniversalBaseModel):
    """
    Optional structured context attached to an error.
    """

    issues: typing.Optional[typing.List[PublicApiValidationIssue]] = None
    field: typing.Optional[str] = None
    column: typing.Optional[str] = None
    invalid_values: typing_extensions.Annotated[
        typing.Optional[typing.List[str]], FieldMetadata(alias="invalidValues")
    ] = None
    allowed_values: typing_extensions.Annotated[
        typing.Optional[typing.List[str]], FieldMetadata(alias="allowedValues")
    ] = None
    value: typing.Optional[str] = None
    retry_after_seconds: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="retryAfterSeconds")
    ] = None
    limit: typing.Optional[int] = None
    remaining: typing.Optional[int] = None
    reset_at: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="resetAt")
    ] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )
