# This file was auto-generated by Fern from our API Definition.

import typing

from ....core import enum

T_Result = typing.TypeVar("T_Result")


class PublicApiErrorCode(enum.StrEnum):
    """
    Machine-readable error code returned by the unstable evaluators API.

    SDKs, CLIs, and agents should branch on `code` rather than parsing the human-readable `message`.
    The HTTP status still indicates the broad error class, while `code` gives the specific failure reason.
    """

    AUTHENTICATION_FAILED = "authentication_failed"
    ACCESS_DENIED = "access_denied"
    INVALID_REQUEST = "invalid_request"
    INVALID_QUERY = "invalid_query"
    INVALID_BODY = "invalid_body"
    INVALID_FILTER_VALUE = "invalid_filter_value"
    INVALID_JSON_PATH = "invalid_json_path"
    INVALID_VARIABLE_MAPPING = "invalid_variable_mapping"
    MISSING_VARIABLE_MAPPING = "missing_variable_mapping"
    DUPLICATE_VARIABLE_MAPPING = "duplicate_variable_mapping"
    RESOURCE_NOT_FOUND = "resource_not_found"
    NAME_CONFLICT = "name_conflict"
    EVALUATOR_PREFLIGHT_FAILED = "evaluator_preflight_failed"
    CONFLICT = "conflict"
    UNPROCESSABLE_CONTENT = "unprocessable_content"
    RATE_LIMITED = "rate_limited"
    METHOD_NOT_ALLOWED = "method_not_allowed"
    INTERNAL_ERROR = "internal_error"

    def visit(
        self,
        authentication_failed: typing.Callable[[], T_Result],
        access_denied: typing.Callable[[], T_Result],
        invalid_request: typing.Callable[[], T_Result],
        invalid_query: typing.Callable[[], T_Result],
        invalid_body: typing.Callable[[], T_Result],
        invalid_filter_value: typing.Callable[[], T_Result],
        invalid_json_path: typing.Callable[[], T_Result],
        invalid_variable_mapping: typing.Callable[[], T_Result],
        missing_variable_mapping: typing.Callable[[], T_Result],
        duplicate_variable_mapping: typing.Callable[[], T_Result],
        resource_not_found: typing.Callable[[], T_Result],
        name_conflict: typing.Callable[[], T_Result],
        evaluator_preflight_failed: typing.Callable[[], T_Result],
        conflict: typing.Callable[[], T_Result],
        unprocessable_content: typing.Callable[[], T_Result],
        rate_limited: typing.Callable[[], T_Result],
        method_not_allowed: typing.Callable[[], T_Result],
        internal_error: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is PublicApiErrorCode.AUTHENTICATION_FAILED:
            return authentication_failed()
        if self is PublicApiErrorCode.ACCESS_DENIED:
            return access_denied()
        if self is PublicApiErrorCode.INVALID_REQUEST:
            return invalid_request()
        if self is PublicApiErrorCode.INVALID_QUERY:
            return invalid_query()
        if self is PublicApiErrorCode.INVALID_BODY:
            return invalid_body()
        if self is PublicApiErrorCode.INVALID_FILTER_VALUE:
            return invalid_filter_value()
        if self is PublicApiErrorCode.INVALID_JSON_PATH:
            return invalid_json_path()
        if self is PublicApiErrorCode.INVALID_VARIABLE_MAPPING:
            return invalid_variable_mapping()
        if self is PublicApiErrorCode.MISSING_VARIABLE_MAPPING:
            return missing_variable_mapping()
        if self is PublicApiErrorCode.DUPLICATE_VARIABLE_MAPPING:
            return duplicate_variable_mapping()
        if self is PublicApiErrorCode.RESOURCE_NOT_FOUND:
            return resource_not_found()
        if self is PublicApiErrorCode.NAME_CONFLICT:
            return name_conflict()
        if self is PublicApiErrorCode.EVALUATOR_PREFLIGHT_FAILED:
            return evaluator_preflight_failed()
        if self is PublicApiErrorCode.CONFLICT:
            return conflict()
        if self is PublicApiErrorCode.UNPROCESSABLE_CONTENT:
            return unprocessable_content()
        if self is PublicApiErrorCode.RATE_LIMITED:
            return rate_limited()
        if self is PublicApiErrorCode.METHOD_NOT_ALLOWED:
            return method_not_allowed()
        if self is PublicApiErrorCode.INTERNAL_ERROR:
            return internal_error()
