# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ....commons.types.deprecation import Deprecation
from ....core.pydantic_utilities import UniversalBaseModel
from ....core.serialization import FieldMetadata


class MetricsResponse(UniversalBaseModel):
    data: typing.List[typing.Dict[str, typing.Any]] = pydantic.Field()
    """
    The metrics data. Each item in the list contains the metric values and dimensions requested in the query.
    Format varies based on the query parameters.
    Histograms will return an array with [lower, upper, height] tuples.
    """

    deprecation: typing_extensions.Annotated[
        typing.Optional[Deprecation], FieldMetadata(alias="_deprecation")
    ] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )
