# This file was auto-generated by Fern from our API Definition.

import typing

from ....core import enum

T_Result = typing.TypeVar("T_Result")


class EvaluatorScope(enum.StrEnum):
    """
    Where an evaluator comes from.

    - `project`: created in your project
    - `managed`: provided by Langfuse
    """

    PROJECT = "project"
    MANAGED = "managed"

    def visit(
        self,
        project: typing.Callable[[], T_Result],
        managed: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is EvaluatorScope.PROJECT:
            return project()
        if self is EvaluatorScope.MANAGED:
            return managed()
