# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import UniversalBaseModel
from ....core.serialization import FieldMetadata
from .prompt_variable_mapping_source import PromptVariableMappingSource


class PromptVariableMappingRead(UniversalBaseModel):
    """
    Connects one prompt variable to data from a target.

    `source` is `null` when the mapping is incomplete.

    Examples
    --------
    from langfuse.unstable.commons import (
        PromptVariableMappingRead,
        PromptVariableMappingSource,
    )

    PromptVariableMappingRead(
        variable="input",
        source=PromptVariableMappingSource.INPUT,
    )
    """

    variable: str = pydantic.Field()
    """
    Prompt variable name without braces.
    """

    source: typing.Optional[PromptVariableMappingSource] = pydantic.Field(default=None)
    """
    Source field populating the variable, or `null` when the mapping is incomplete.
    """

    json_path: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="jsonPath")
    ] = pydantic.Field(default=None)
    """
    Optional JSONPath selector applied to the selected source.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )
