# This file was auto-generated by Fern from our API Definition.

from .create_event_body import CreateEventBody
import typing
import datetime as dt
import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2


class CreateSpanBody(CreateEventBody):
    end_time: typing.Optional[dt.datetime] = pydantic.Field(
        alias="endTime", default=None
    )

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
