# This file was auto-generated by Fern from our API Definition.

import typing

ObservationType = typing.Union[
    typing.Literal[
        "SPAN",
        "GENERATION",
        "EVENT",
        "AGENT",
        "TOOL",
        "CHAIN",
        "RETRIEVER",
        "EVALUATOR",
        "EMBEDDING",
        "GUARDRAIL",
    ],
    typing.Any,
]
