# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        CreateDashboardPlacementRequest,
        CreateDashboardPlacementRequest_Preset,
        CreateDashboardPlacementRequest_Widget,
        CreateDashboardRequest,
        CreatePresetPlacement,
        CreateWidgetPlacement,
        Dashboard,
        DashboardDefinition,
        DashboardList,
        DashboardPlacement,
        DashboardPlacement_Preset,
        DashboardPlacement_Widget,
        DeleteDashboardPlacementResponse,
        DeleteDashboardResponse,
        PresetPlacement,
        UpdateDashboardPlacementRequest,
        UpdateDashboardRequest,
        WidgetPlacement,
    )
_dynamic_imports: typing.Dict[str, str] = {
    "CreateDashboardPlacementRequest": ".types",
    "CreateDashboardPlacementRequest_Preset": ".types",
    "CreateDashboardPlacementRequest_Widget": ".types",
    "CreateDashboardRequest": ".types",
    "CreatePresetPlacement": ".types",
    "CreateWidgetPlacement": ".types",
    "Dashboard": ".types",
    "DashboardDefinition": ".types",
    "DashboardList": ".types",
    "DashboardPlacement": ".types",
    "DashboardPlacement_Preset": ".types",
    "DashboardPlacement_Widget": ".types",
    "DeleteDashboardPlacementResponse": ".types",
    "DeleteDashboardResponse": ".types",
    "PresetPlacement": ".types",
    "UpdateDashboardPlacementRequest": ".types",
    "UpdateDashboardRequest": ".types",
    "WidgetPlacement": ".types",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(
            f"No {attr_name} found in _dynamic_imports for module name -> {__name__}"
        )
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(
            f"Failed to import {attr_name} from {module_name}: {e}"
        ) from e
    except AttributeError as e:
        raise AttributeError(
            f"Failed to get {attr_name} from {module_name}: {e}"
        ) from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "CreateDashboardPlacementRequest",
    "CreateDashboardPlacementRequest_Preset",
    "CreateDashboardPlacementRequest_Widget",
    "CreateDashboardRequest",
    "CreatePresetPlacement",
    "CreateWidgetPlacement",
    "Dashboard",
    "DashboardDefinition",
    "DashboardList",
    "DashboardPlacement",
    "DashboardPlacement_Preset",
    "DashboardPlacement_Widget",
    "DeleteDashboardPlacementResponse",
    "DeleteDashboardResponse",
    "PresetPlacement",
    "UpdateDashboardPlacementRequest",
    "UpdateDashboardRequest",
    "WidgetPlacement",
]
