# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ....core.serialization import FieldMetadata
from .chat_message_with_placeholders import ChatMessageWithPlaceholders


class Prompt_Chat(UniversalBaseModel):
    type: typing.Literal["chat"] = "chat"
    prompt: typing.List[ChatMessageWithPlaceholders]
    name: str
    version: int
    config: typing.Any
    labels: typing.List[str]
    tags: typing.List[str]
    commit_message: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="commitMessage")
    ] = None
    resolution_graph: typing_extensions.Annotated[
        typing.Optional[typing.Dict[str, typing.Any]],
        FieldMetadata(alias="resolutionGraph"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class Prompt_Text(UniversalBaseModel):
    type: typing.Literal["text"] = "text"
    prompt: str
    name: str
    version: int
    config: typing.Any
    labels: typing.List[str]
    tags: typing.List[str]
    commit_message: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="commitMessage")
    ] = None
    resolution_graph: typing_extensions.Annotated[
        typing.Optional[typing.Dict[str, typing.Any]],
        FieldMetadata(alias="resolutionGraph"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


Prompt = typing_extensions.Annotated[
    typing.Union[Prompt_Chat, Prompt_Text], pydantic.Field(discriminator="type")
]
