# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import UniversalBaseModel
from ....core.serialization import FieldMetadata


class CreateWidgetPlacement(UniversalBaseModel):
    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Server-generated when omitted.
    """

    widget_id: typing_extensions.Annotated[str, FieldMetadata(alias="widgetId")]
    x: typing.Optional[int] = pydantic.Field(default=None)
    """
    Grid column (12-column grid). Defaults to `0`.
    """

    y: typing.Optional[int] = pydantic.Field(default=None)
    """
    Grid row. Defaults to the first row below all existing tiles.
    """

    width: typing.Optional[int] = pydantic.Field(default=None)
    """
    Width in grid columns. Defaults to `6`.
    """

    height: typing.Optional[int] = pydantic.Field(default=None)
    """
    Height in grid rows. Defaults to `6`.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )
