# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import UniversalBaseModel


class UpdateDashboardPlacementRequest(UniversalBaseModel):
    x: typing.Optional[int] = pydantic.Field(default=None)
    """
    Grid column (12-column grid).
    """

    y: typing.Optional[int] = pydantic.Field(default=None)
    """
    Grid row.
    """

    width: typing.Optional[int] = pydantic.Field(default=None)
    """
    Width in grid columns.
    """

    height: typing.Optional[int] = pydantic.Field(default=None)
    """
    Height in grid rows.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )
