# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .otel_resource import OtelResource
from .otel_scope_span import OtelScopeSpan


class OtelResourceSpan(UniversalBaseModel):
    """
    Represents a collection of spans from a single resource as per OTLP specification
    """

    resource: typing.Optional[OtelResource] = pydantic.Field(default=None)
    """
    Resource information
    """

    scope_spans: typing_extensions.Annotated[
        typing.Optional[typing.List[OtelScopeSpan]], FieldMetadata(alias="scopeSpans")
    ] = pydantic.Field(default=None)
    """
    Array of scope spans
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
