# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import UniversalBaseModel
from .otel_attribute_value import OtelAttributeValue


class OtelAttribute(UniversalBaseModel):
    """
    Key-value attribute pair for resources, scopes, or spans
    """

    key: typing.Optional[str] = pydantic.Field(default=None)
    """
    Attribute key (e.g., "service.name", "langfuse.observation.type")
    """

    value: typing.Optional[OtelAttributeValue] = pydantic.Field(default=None)
    """
    Attribute value
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )
