# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .otel_attribute import OtelAttribute


class OtelSpan(UniversalBaseModel):
    """
    Individual span representing a unit of work or operation
    """

    trace_id: typing_extensions.Annotated[
        typing.Optional[typing.Any], FieldMetadata(alias="traceId")
    ] = pydantic.Field(default=None)
    """
    Trace ID (16 bytes, hex-encoded string in JSON or Buffer in binary)
    """

    span_id: typing_extensions.Annotated[
        typing.Optional[typing.Any], FieldMetadata(alias="spanId")
    ] = pydantic.Field(default=None)
    """
    Span ID (8 bytes, hex-encoded string in JSON or Buffer in binary)
    """

    parent_span_id: typing_extensions.Annotated[
        typing.Optional[typing.Any], FieldMetadata(alias="parentSpanId")
    ] = pydantic.Field(default=None)
    """
    Parent span ID if this is a child span
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Span name describing the operation
    """

    kind: typing.Optional[int] = pydantic.Field(default=None)
    """
    Span kind (1=INTERNAL, 2=SERVER, 3=CLIENT, 4=PRODUCER, 5=CONSUMER)
    """

    start_time_unix_nano: typing_extensions.Annotated[
        typing.Optional[typing.Any], FieldMetadata(alias="startTimeUnixNano")
    ] = pydantic.Field(default=None)
    """
    Start time in nanoseconds since Unix epoch
    """

    end_time_unix_nano: typing_extensions.Annotated[
        typing.Optional[typing.Any], FieldMetadata(alias="endTimeUnixNano")
    ] = pydantic.Field(default=None)
    """
    End time in nanoseconds since Unix epoch
    """

    attributes: typing.Optional[typing.List[OtelAttribute]] = pydantic.Field(
        default=None
    )
    """
    Span attributes including Langfuse-specific attributes (langfuse.observation.*)
    """

    status: typing.Optional[typing.Any] = pydantic.Field(default=None)
    """
    Span status object
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
