# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from .raw_client import AsyncRawLegacyClient, RawLegacyClient

if typing.TYPE_CHECKING:
    from .score_v1.client import AsyncScoreV1Client, ScoreV1Client


class LegacyClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawLegacyClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._score_v1: typing.Optional[ScoreV1Client] = None

    @property
    def with_raw_response(self) -> RawLegacyClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawLegacyClient
        """
        return self._raw_client

    @property
    def score_v1(self):
        if self._score_v1 is None:
            from .score_v1.client import ScoreV1Client  # noqa: E402

            self._score_v1 = ScoreV1Client(client_wrapper=self._client_wrapper)
        return self._score_v1


class AsyncLegacyClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawLegacyClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._score_v1: typing.Optional[AsyncScoreV1Client] = None

    @property
    def with_raw_response(self) -> AsyncRawLegacyClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawLegacyClient
        """
        return self._raw_client

    @property
    def score_v1(self):
        if self._score_v1 is None:
            from .score_v1.client import AsyncScoreV1Client  # noqa: E402

            self._score_v1 = AsyncScoreV1Client(client_wrapper=self._client_wrapper)
        return self._score_v1
