name: Check availability of packages

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies using pip
        run: |
          pip install llama-index-callbacks-langfuse langfuse
