name: Check availability of packages

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies using pip
        run: |
          pip install llama-index-callbacks-langfuse langfuse
